name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  record: ^5.0.4  # untuk recording audio
  path_provider: ^2.1.1  # untuk menyimpan file audio
  audioplayers: ^5.2.1 
  d_info: ^0.2.0
  d_button: ^0.0.10
  d_input: ^0.1.3
  d_method: ^0.2.6
  d_session: ^0.0.2
  extended_image: ^8.2.0 
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
