name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  record: ^5.0.4  # untuk recording audio
  path_provider: ^2.1.1  # untuk menyimpan file audio
  audioplayers: ^5.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
